### PR TITLE
Remove redundant postcode validation

### PR DESCRIPTION
**Pull request by mbarton**
`/validate` does the [same underlying database lookup](https://github.com/ideal-postcodes/postcodes.io/blob/656f16bb2cc9807f4ad3adada9c83658daf269c2/src/app/controllers/postcodes_controller.ts#L40) at their end as the normal API so we don't need the additional call. This makes the API about twice as fast.

*Before*

```
time curl 'http://localhost:8001/index_of_multiple_deprivation_quantile?postcode=W1A1AA&quantile=5'
{"result":{"rank":15472,"requested_quantile":5,"requested_quantile_name":"quintile","data_quantile":3,"country":"england","error":null}}
real    0m0.186s
user    0m0.002s
sys     0m0.003s
```

*After*

```
time curl 'http://localhost:8001/index_of_multiple_deprivation_quantile?postcode=W1A1AA&quantile=5'
{"result":{"rank":15472,"requested_quantile":5,"requested_quantile_name":"quintile","data_quantile":3,"country":"england","error":null}}
real    0m0.103s
user    0m0.002s
sys     0m0.003s
```

### CODE REVIEW

**Comment by pacharanero** [comment]
I can't see any difference between Before and After in the first post...

**Comment by mbarton** [comment]
Whoops, have updated with the correct timings

**Comment by pacharanero** [comment]
Aha yes much faster

**Comment by anchit-chandran** [comment]
this is a fantastically simple improvement, really good catch! LGTM

**Pull request merged**
